@urlDev=http://localhost:3001

### add data
POST {{urlDev}}/record
Content-Type: application/json

{
    "recordInfo":{
        "value" : 13,
        "sensorId" : 1,
        "sensorName":"Humidity",
        "recordId":1
    }
}

###get data
GET {{urlDev}}/record?limit=1&offset=1
Content-Type: application/json